os:
  - linux
  # - osx
  # - windows

dist: xenial
sudo: require
language: cpp

script:
  - bash bin/clean
  # - bash bin/ci
  # - bash bin/configure 
  # - bash bin/build
  # - bash bin/run-unit-tests 

deploy:
  provider: releases
  api_key: df91e078d1a9c32cf11ba754a3886642d6b34cd9    
  file_glob: true
  # file: build/release/package/robo3t*
  file: bin/ci
  on:
    repo: simsekgokhan/robomongo
  skip_cleanup: true
  # Deploy draft release
  draft: true
  # Deploy only if the build is a tagged build
  # on:
  # tags: true  

# end of file
