os:
- linux
dist: xenial
sudo: require
language: cpp
script:
- bash bin/clean
deploy:
  provider: releases
  api_key:
    secure: cPnNGWA2jiGl2BzaLB+GGi3qhkYfxQkZFuBObj3lF37WsbWER2e8VbUM0B1bAQYHu8v4BExzdwmrDBhaxXj9hmRwXI99cLq+SB1SUTwm6G/jSaY22Ofzk5XFnx0OiXEPkSfaqqvSq4GfkC31TlldboKyhF209FZe+qd7pXhCgK8IW2IgLALVgtUONbs5ZzILtNQffvpCl9QdNzbV4kO9VNsltRejviKzic97rBY2iBJt0WBmpCSH4366yoqiZpUECk1B32aDIJmDES0CozWBUHLQ22Rqls6ALgbDAdk3yx+VvCXC/bwgO3p92kdQaMEqDuzQfjeidYczAA08+SDRlczO7hm6QcsPdCpZapoYpXlpVETGPtpCB4qeg1W1JcddsxFfK2K2PusP+0IKpSIRR0PvqGyhxTtOEZE7NWIr8UGlRN8IZ0KEZrP+fJCxW1RoSNze5Uw6+xPKSutocRsxSIC1vxzxBQApBV9WlzpxhWazsn/puO5Qs5Xwig3MQNwQBcjVCIjFp2npxPgKaX42xu0QHHujnSj1w7+CUdBPLiItLInKegvHmbjv5hHyJ9yEk8jr5Pjl1H0jGv/wYv+K+B1jZwnvhMb0y5WKmMq8T8N3hhHTl3R/hmURnjWPBA+cx6+/zeSDs2+Elf8d0k373Pp0isDSx1TSS4FuEtI1/VU=
  file: '"bin/ci"'
  on:
    repo: simsekgokhan/robomongo
